name: Mon premier workflow
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
env:
  VARIABLE_NAME: value
  SUPER_SECRET: ${{ secrets.SECRET_NAME }}
jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: display variable
        run: echo ${{ env.VARIABLE_NAME }}
      - name: Use a secret
        run: echo $SUPER_SECRET
      - name: Checkout
        uses: actions/checkout@v4
      - name: Listing files
        run: ls -al
      - name: List files
        run: ls -al

    
